apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ncas-general-cdl-creator-ingress 
  namespace: ncas-data-activity
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: "true"
    nginx.ingress.kubernetes.io/permanent-redirect-code: "301"
spec:
  tls:
  - hosts:
      - force-test.ddns.net
    secretName: ncas-general-cdl-creator-tls
  rules:
  - host: force-test.ddns.net
    http:
      paths:
      - path: /ncas-general-cdl(/|$)(.*)
        pathType: Prefix 
        backend:
          service:
            name: ncas-general-cdl-creator-frontend-service
            port:
              number: 80
      - path: /ncas-general-cdl
        pathType: Exact
        backend:
          service:
            name: ncas-general-cdl-creator-frontend-service
            port:
              number: 80


