apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ncas-general-cdl-creator-ingress 
  namespace: ncas-data-activity
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
      - force-test.ddns.net
    secretName: ncas-general-cdl-creator-tls
  rules:
  - host: force-test.ddns.net
    http:
      paths:
      - path: /ncas-general-cdl
        pathType: ImplementationSpecific
        backend:
          service:
            name: ncas-general-cdl-creator-frontend-service
            port:
              number: 3080

